services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - /certs:/certs # set your path to certs as as in env
        env_file:
            - .env
        depends_on:
            db:
                condition: service_healthy
        ports:
            - 8000:8000
            - 8443:8443

    db:
        image: postgres:16-alpine
        restart: always
        volumes:
            - ./app/db/data:/var/lib/postgresql/data
            - ./app/db/migrations:/docker-entrypoint-initdb.d
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: app
            TZ: UTC
            PGTZ: UTC
        ports:
            - 5432:5432
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    "psql -U $$POSTGRES_USER -d $$POSTGRES_DB -c 'SELECT 1' || exit 1",
                ]
            interval: 30s
            timeout: 60s
            retries: 5
            start_period: 80s
