CREATE TABLE IF NOT EXISTS article_management.comments (
	id SERIAL PRIMARY KEY,
	body TEXT NOT NULL,
	user_id INTEGER REFERENCES article_management.users (id) ON DELETE CASCADE,
	article_id INTEGER REFERENCES article_management.articles (id) ON DELETE CASCADE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
